name: Test annotations

on:
  workflow_dispatch:
    inputs:
      test-multiline:
        type: string
        default: |
          Tags generated:
          repo-tag/onedhtads/jasdhjd:123123-asdfa1-f3
          repo-tag/onedhtads/jasdhjd:123123-asdfa1-f3
          repo-tag/onedhtads/jasdhjd:123123-asdfa1-f3

jobs:

  annotate:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |

          lines="$(echo '${{ inputs.test-multiline }}' | tr '\n' '%0A')"
        
          echo '::notice::Test Single Line'
          echo '::notice::${{ inputs.test-multiline }}'
          echo '::notice::${lines}'
