name: Test annotations

on:
  workflow_dispatch:
  push:

jobs:

  annotate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            location1/image
            locationB/image
            locationC/image
      - shell: bash
        run: |

          lines="$(echo '${{ steps.meta.outputs.tags }}' | tr '\n' ', ')"
          lines2="$(echo '${{ steps.meta.outputs.tags }}' | tr '\n' '\%0A')"
          lines3="$(echo '${{ steps.meta.outputs.tags }}' | tr '\n' '%0A')"
        
          echo '::notice::Test Single Line'
          echo "::notice::Bare - '${{ steps.meta.outputs.tags }}'"
          echo "::notice::1Tags Generated=[${lines}]"
          echo "::notice::2Tags Generated=[" '${steps.meta.outputs.tags}' ']'
          echo "::notice::3Tags Generated=[" ${lines3} "]"
