name: Test annotations

on:
  workflow_dispatch:
  push:

jobs:

  annotate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            location1/image
            locationB/image
            locationC/image
      - shell: bash
        run: |

          lines="$(echo '${{ steps.meta.outputs.tags }}' | tr '\n' ', ')"
        
          echo '::notice::Test Single Line'
          echo '::notice::${{ steps.meta.outputs.tags }}'
          echo "::notice::Tags Generated=[${lines}]"
