name: Test annotations

on:
  workflow_dispatch:
    inputs:
      test-multiline:
        type: string
        default: |
          repo-tag/onedhtads/jasdhjd:123123-asdfa1-f3
          repo-tag/onedhtads/jasdhjd:123123-asdfa1-f3
          repo-tag/onedhtads/jasdhjd:123123-asdfa1-f3
          repo-tag/onedhtads/jasdhjd:123123-asdfa1-f3
          repo-tag/onedhtads/jasdhjd:123123-asdfa1-f3
          repo-tag/onedhtads/jasdhjd:123123-asdfa1-f3
          repo-tag/onedhtads/jasdhjd:123123-asdfa1-f3
          repo-tag/onedhtads/jasdhjd:123123-asdfa1-f3
          repo-tag/onedhtads/jasdhjd:123123-asdfa1-f3

jobs:

  annotate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            location1/image
            locationB/image
            locationC/image
      - shell: bash
        run: |

          lines="$(echo '${{ inputs.test-multiline }}' | tr '\n' ', ')"
        
          echo '::notice::Test Single Line'
          echo '::notice::${{ inputs.steps.meta.outputs.tags }}'
          echo "::notice::Tags Generated=[${lines}]"
