name: Generic Test
run-name: Running ${{ inputs.testname }} on ${{ inputs.environment }}

on:
  workflow_dispatch:
  workflow_call:

env:
  TEST: "algo"

jobs:
  example_job:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        run: echo env
