name: Generic Regressions
on:
  workflow_dispatch:
  workflow_call:

jobs:

  check:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world

  testsA:
    needs: check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [1, 2, 3]
        test: ["one", "two"]
    steps:
      - run: echo Hello World
      
  testsB:
    needs: check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - version: 1
            test: one
          - version: 2
            test: two
          - version: 3
            test: three
        exclude:
          - version: 1
          - version: 2
    steps:
      - run: echo Hello World
