name: Generic Deploy
on:
  workflow_call:

jobs:

  register:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world

  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 5
      - run: sleep 5
      - run: sleep 5
      - run: sleep 5
